### ISSUE TITLE
PyVistaQF VTK compatibility help, AttributeError: 'StructuredGrid' object has no attribute 'point_arrays'

### ISSUE THREAD

**Issue by mathfire** [QF-Error-Tracking/QFVD5#18]
**Describe the bug**

  placecam = np.int(plot_params['PLACECAM'])
	 - read movie data
	 - add initial plots
Traceback (most recent call last):
  File "/Users/amasarie/Research/QF_5.2.3/scripts/postprocessing/python3/PyVistaQF.py", line 1006, in <module>
    main(sys.argv[1], pyfilename)
  File "/Users/amasarie/Research/QF_5.2.3/scripts/postprocessing/python3/PyVistaQF.py", line 979, in main
    generate_movie_fire('standin.mp4', qu, qf, flags, terrain_box, terrain_top, plot_params, output_folder)
  File "/Users/amasarie/Research/QF_5.2.3/scripts/postprocessing/python3/PyVistaQF.py", line 800, in generate_movie_fire
    add_topo_plot(terrain_box, terrain_top, plotter, cbar_args, 10, False)
  File "/Users/amasarie/Research/QF_5.2.3/scripts/postprocessing/python3/PyVistaQF.py", line 297, in add_topo_plot
    terrain_top.point_arrays['heights'] = terrain_top.points[:, 2]
  File "/Users/amasarie/.local/lib/python3.9/site-packages/pyvista/core/dataset.py", line 122, in __getattr__
    return super().__getattribute__(item)
AttributeError: 'StructuredGrid' object has no attribute 'point_arrays'
(base) cotopaxi:python3 amasarie$ 

**To Reproduce**
Link to input files [e.g. Google Drive or Box]
or
Email: Dev Team will reach out if input files are needed

	Here’s my original call (its PyVistaQF to visual a 500m watershed focus area)
	((base) cotopaxi:python3 amasarie$ python3 PyVistaQF.py /Users/amasarie/Research/QF_5.2.3/proj/Chambers-500m/

**Desktop (please complete the following information):**
 - QF Version [e.g. QFVD5.0.0]. QF_5.2.3
 - OS: [e.g. Ubuntu, Mac]  Ubuntu Bionic Beaver LTS 18.04 and above
 - Hardware SPECs [If applicable] MacBook Pro M1 (same issue results)

**Screenshots**

	Thanks will do - 
<img width="1070" alt="QF_GitBub_02" src="https://github.com/QF-Error-Tracking/QFVD5/assets/32973762/245ec28b-0768-46e4-ad64-eeb55413693c">

**Comment by zacharycope0** [comment]
Could you clean up this issue and tag @drobinson6045. In addition to the error message, you will need to explain your steps/desired outcome, post a link to your input files, and share the Pyvista version you are using.

**Comment by amarcozzi** [comment]
Hey @mathfire I've run into this before. The PyVistaQF script uses features from a several year old version of Pyvista which are long since deprecated. It's possible to build the correct environment using the packages in the pip or conda requirements file, but there's a very narrow range of Python versions which are capable of satisfying the requirements. I was able to get it to work with Python 3.8.16.

**Comment by ntutland** [comment]
I was able to get more of the code to run by changing "point_arrays" to "point_data" for StructuredGrid objects, and changing "cell_arrays" to "cell_data" for UnstructuredGrid objects. However, now the code is just sitting there, not throwing an error, but also not completing the task -- not sure if that is related or not. I'll try with python 3.8.16 and see what happens

**Comment by mathfire** [comment]
Yes! This solves it!!  Thanks for the update, glad this triggered in my email too. 

Again, sorry for not cleaning up this issue!!
I will post another on here soon, better format all around,

I continually get the versioning wrong too!! So that has been my culprit for this and other issues.
Better version control for me has led to the code running better,
Anaconda environments seem to be the way to go, which thanks to Zach and Daniel taught me all that - NMC does have Anaconda Navigator on our machines, which helps me stay organized without much hassle on the MacBook M2 from NMC.
I attached a screenshot that highlights version control -

All the best,
Alex
<img width="1349" alt="Anaconda Navigator" src="https://github.com/QF-Error-Tracking/QFVD5/assets/32973762/d5685d5f-2b22-40ae-961b-6fecf7e8affe">
